// Mocks generated by Mockito 5.0.3 from annotations
// in run_bus/test/features/data/repository/geocoding_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/adapters/abs_geocoding.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeGeocodingResponse extends _i1.Fake implements _i2.GeocodingResponse {
}

/// A class which mocks [IGeocoding].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGeocoding extends _i1.Mock implements _i2.IGeocoding {
  MockIGeocoding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.GeocodingResponse> coordToAndress(double? lng, double? lon) =>
      (super.noSuchMethod(Invocation.method(#coordToAndress, [lng, lon]),
              returnValue: Future.value(_FakeGeocodingResponse()))
          as _i3.Future<_i2.GeocodingResponse>);
}
