// Mocks generated by Mockito 5.0.2 from annotations
// in run_bus/test/features/data/repository/integration_area_repository_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/apis/integration_area.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IIntegrationAreaApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIIntegrationAreaApi extends _i1.Mock
    implements _i2.IIntegrationAreaApi {
  MockIIntegrationAreaApi() {
    _i1.throwOnMissingStub(this);
  }
}
