// Mocks generated by Mockito 5.0.3 from annotations
// in run_bus/test/features/data/repository/location_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/adapters/abs_location.dart'
    as _i2;
import 'package:run_bus/features/data/external/drivers/location_adapter.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeLocationResponse extends _i1.Fake implements _i2.LocationResponse {}

/// A class which mocks [LocationAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationAdapter extends _i1.Mock implements _i3.LocationAdapter {
  MockLocationAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LocationResponse> getCurrentPosition() =>
      (super.noSuchMethod(Invocation.method(#getCurrentPosition, []),
              returnValue: Future.value(_FakeLocationResponse()))
          as _i4.Future<_i2.LocationResponse>);
}
