// Mocks generated by Mockito 5.0.3 from annotations
// in run_bus/test/features/data/repository/reference_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/adapters/abs_reference.dart'
    as _i3;
import 'package:run_bus/features/data/models/reference_model.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeReferenceModel extends _i1.Fake implements _i2.ReferenceModel {}

/// A class which mocks [IReference].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReference extends _i1.Mock implements _i3.IReference {
  MockIReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ReferenceModel> findReferenceByDistrict(String? district) =>
      (super.noSuchMethod(
              Invocation.method(#findReferenceByDistrict, [district]),
              returnValue: Future.value(_FakeReferenceModel()))
          as _i4.Future<_i2.ReferenceModel>);
}
