// Mocks generated by Mockito 5.0.3 from annotations
// in run_bus/test/features/data/repository/version_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/adapters/abs_version.dart'
    as _i3;
import 'package:run_bus/features/data/models/version_model.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeVersionModel extends _i1.Fake implements _i2.VersionModel {}

/// A class which mocks [IVersion].
///
/// See the documentation for Mockito's code generation for more information.
class MockIVersion extends _i1.Mock implements _i3.IVersion {
  MockIVersion() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VersionModel?> lastVersion() =>
      (super.noSuchMethod(Invocation.method(#lastVersion, []),
              returnValue: Future.value(_FakeVersionModel()))
          as _i4.Future<_i2.VersionModel?>);
}
