// Mocks generated by Mockito 5.0.2 from annotations
// in run_bus/test/features/domain/usecase/current_location_user_use_case_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:run_bus/features/data/external/drivers/location_verify_adapter.dart'
    as _i6;
import 'package:run_bus/features/domain/repositories/geocoding_repository.dart'
    as _i3;
import 'package:run_bus/features/domain/repositories/integration_area_repository.dart'
    as _i5;
import 'package:run_bus/features/domain/repositories/location_repository.dart'
    as _i2;
import 'package:run_bus/features/domain/repositories/reference_repository.dart'
    as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ILocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationRepository extends _i1.Mock
    implements _i2.ILocationRepository {
  MockILocationRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [IGeocodingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGeocodingRepository extends _i1.Mock
    implements _i3.IGeocodingRepository {
  MockIGeocodingRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [IReferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReferenceRepository extends _i1.Mock
    implements _i4.IReferenceRepository {
  MockIReferenceRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ILocationAreaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationAreaRepository extends _i1.Mock
    implements _i5.ILocationAreaRepository {
  MockILocationAreaRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ILocationVerifyAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationVerifyAdapter extends _i1.Mock
    implements _i6.ILocationVerifyAdapter {
  MockILocationVerifyAdapter() {
    _i1.throwOnMissingStub(this);
  }
}
